name: Build 3DS CIA

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: devkitpro/devkitarm

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build 3DS homebrew
        run: |
          make

      - name: Check output
        run: ls -la

      - name: Build CIA
        run: |
          mkdir out
          cp *.3dsx out/ || true

          for f in out/*.3dsx; do
            [ -f "$f" ] || continue
            name=$(basename "$f" .3dsx)

            makerom -f cia \
              -o "$name.cia" \
              -target t \
              -exefslogo \
              -elf "$f"
          done

      - name: Upload CIA
        uses: actions/upload-artifact@v4
        with:
          name: CIA
          path: out/*.cia
